// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk2Wg-nDrMUOmG8AcB6L8l8Q10uqSFyxs',
    appId: '1:645645647567:web:6d02a30a36ebeec27281ba',
    messagingSenderId: '645645647567',
    projectId: 'panaderia-delicia-web',
    authDomain: 'panaderia-delicia-web.firebaseapp.com',
    storageBucket: 'panaderia-delicia-web.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmNHuJkSavhNotT9hIUpjmwE0mMFHACQ0',
    appId: '1:645645647567:android:0781ac0686d777817281ba',
    messagingSenderId: '645645647567',
    projectId: 'panaderia-delicia-web',
    storageBucket: 'panaderia-delicia-web.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR13GcZm3EvZecSCvHZ8XlyIxLnZOcuwE',
    appId: '1:645645647567:ios:c03abbe1ecd568ae7281ba',
    messagingSenderId: '645645647567',
    projectId: 'panaderia-delicia-web',
    storageBucket: 'panaderia-delicia-web.firebasestorage.app',
    iosBundleId: 'com.example.panaderiaDeliciaWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR13GcZm3EvZecSCvHZ8XlyIxLnZOcuwE',
    appId: '1:645645647567:ios:c03abbe1ecd568ae7281ba',
    messagingSenderId: '645645647567',
    projectId: 'panaderia-delicia-web',
    storageBucket: 'panaderia-delicia-web.firebasestorage.app',
    iosBundleId: 'com.example.panaderiaDeliciaWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk2Wg-nDrMUOmG8AcB6L8l8Q10uqSFyxs',
    appId: '1:645645647567:web:3bc3a6c0ced027d27281ba',
    messagingSenderId: '645645647567',
    projectId: 'panaderia-delicia-web',
    authDomain: 'panaderia-delicia-web.firebaseapp.com',
    storageBucket: 'panaderia-delicia-web.firebasestorage.app',
  );
}
